### ISSUE TITLE
Please upgrade branch v4.11.x-imx5 to v4.11.2

### ISSUE THREAD

**Issue by ZupoLlask** [RobertCNelson/armv5_devel#1]
Hi Robert,

Can you please upgrade branch v4.11.x-imxv5 from Kernel v4.11-rc2 to Kernel v4.11.2?

I'm available for making tests or something else helpfull within my reach.

Thanks! :-)

**Comment by RobertCNelson** [comment]
@ZupoLlask in version.sh just change -rc2 to .2 then re-run ./build_kernel.sh

Regards,

**Comment by ZupoLlask** [comment]
Fair enough! Thanks for the help and for your work! :-)
